# Generated by Django 5.2.4 on 2025-10-03 06:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='crunchbase',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tool_images/'),
        ),
        migrations.AddField(
            model_name='tool',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
