# Generated by Django 5.2.4 on 2025-10-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_created_at_tool_crunchbase_tool_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='crunchbase',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='website',
        ),
        migrations.AddField(
            model_name='tool',
            name='pricing',
            field=models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium'), ('Freemium', 'Freemium')], default='Free', max_length=10),
        ),
        migrations.AddField(
            model_name='tool',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
