# Generated by Django 5.2.4 on 2025-10-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_remove_tool_crunchbase_remove_tool_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium'), ('Freemium', 'Freemium')], default='Free', max_length=10),
        ),
    ]
