# Generated by Django 5.2.4 on 2025-10-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_alter_tool_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='tags',
        ),
        migrations.AddField(
            model_name='tool',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=200),
        ),
    ]
