# Generated by Django 5.2.4 on 2025-10-03 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_remove_tool_tags_tool_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_tools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
