# Generated by Django 5.2.4 on 2025-10-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_tool_upvoted_by_alter_tool_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
