# Generated by Django 5.2.4 on 2025-10-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_alter_tool_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('AI Tools', 'AI Tools'), ('Productivity', 'Productivity'), ('Marketing', 'Marketing'), ('Design', 'Design'), ('Development', 'Development'), ('Education', 'Education'), ('Finance', 'Finance')], default='AI Tools', max_length=50),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
