# Generated by Django 5.2.4 on 2025-10-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_alter_tool_category_delete_tag_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('AI Art', 'AI Art'), ('AI Tools', 'AI Tools'), ('App Development', 'App Development'), ('Automation', 'Automation'), ('Blockchain', 'Blockchain'), ('Career', 'Career'), ('Cloud Computing', 'Cloud Computing'), ('Copywriting', 'Copywriting'), ('Cryptocurrency', 'Cryptocurrency'), ('Customer Support', 'Customer Support'), ('Cybersecurity', 'Cybersecurity'), ('Data Analysis', 'Data Analysis'), ('Design', 'Design'), ('Deep Learning', 'Deep Learning'), ('E-commerce', 'E-commerce'), ('Education', 'Education'), ('Entrepreneurship', 'Entrepreneurship'), ('Fitness', 'Fitness'), ('Food & Beverages', 'Food & Beverages'), ('Gaming', 'Gaming'), ('Health', 'Health'), ('HR', 'HR'), ('Investing', 'Investing'), ('Legal', 'Legal'), ('Lifestyle', 'Lifestyle'), ('Machine Learning', 'Machine Learning'), ('Marketing', 'Marketing'), ('Mental Health', 'Mental Health'), ('Music', 'Music'), ('News', 'News'), ('Personal Finance', 'Personal Finance'), ('Photography', 'Photography'), ('Product Management', 'Product Management'), ('Productivity', 'Productivity'), ('Real Estate', 'Real Estate'), ('Robotics', 'Robotics'), ('SEO', 'SEO'), ('Social Media', 'Social Media'), ('Sports', 'Sports'), ('Startups', 'Startups'), ('Travel', 'Travel'), ('UI/UX', 'UI/UX'), ('Video Editing', 'Video Editing'), ('VR/AR', 'VR/AR'), ('Web Development', 'Web Development'), ('Writing', 'Writing'), ('IoT', 'IoT'), ('Networking', 'Networking')], default='AI Tools', max_length=50),
        ),
    ]
